### ISSUE TITLE
Špatný atribut type u inputu s číslem

### ISSUE THREAD

**Issue by Nodonisko** [ktstudio/WP-Framework#2]
->setInputType(KT_Field_Validator::INTEGER) nastaví type="integer" správně to má být type="number"

**Comment by kocifaj** [comment]
Ahoj, díky za feedback v popisovaném případě je to trochu špatně použité. Funkce SetInputType() nastavuje typ inputu. Ale volaná konstata KT_Field_Validator::INTEGER je z jiného soudku a používá se pro funkci addRule(); V tém případě by se mělo jednat o použítí:

setInputType(KT_Text_Field::INPUT_NUMBER)

Konstanta validátoru je určena pouze pro přesné typy hodnot, které se mají kontrolovat. Nikoliv však pro typy inputů.

**Comment by Nodonisko** [comment]
Oki, díky :-)
Dne 21. 10. 2015 7:34 napsal uživatel "Tomáš Kocifaj" <
notifications@github.com>:
