### ISSUE TITLE
Špatný parametr

### ISSUE THREAD

**Issue by Nodonisko** [ktstudio/WP-Framework#3]
Nemělo by [zde](https://github.com/ktstudio/WP-Framework/blob/master/core/classes/form/kt_form_fieldset.inc.php#L309) být namísto $fields $fieldsCollection?

**Comment by Nodonisko** [comment]
Tak jsem neodolal a vyzkoušel pull request :-)

**Comment by hlavacm** [comment]
Jo, díky za opravu :+1:
