### ISSUE TITLE
KT_WP_Editor_Field - setOption()

### ISSUE THREAD

**Issue by petrpojer** [ktstudio/WP-Framework#8]
Ve funkci setOption() u KT_WP_Editor_Field by mělo být "return $this;", jinak není možné nastavit více hodnot naráz, a PHP vrací chybu "Fatal error: Call to a member function setOption() on a non-object".

**Comment by hlavacm** [comment]
Pravdu máš, opraveno v aktuálním developu (8da3ccb) a po vydání to bude v další verzi...
